name: IrelandStatistics application workflow
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Maven dependencies
        working-directory: .
        run: ./mvnw --batch-mode clean package

#      - name: Run tests
#        run: mvn --batch-mode --update-snapshots verify
