name: IrelandStatistics application workflow
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  project-build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Maven dependencies
        working-directory: .
        run: ./mvnw --batch-mode clean package

      - name: Run tests
        working-directory: .
        run: ./mvnw --batch-mode --update-snapshots verify

  docker-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    needs:
      - project-build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: chrisloveireland/ireland-statistics:latest

  Orcle-cloud-Deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    needs:
      - docker-build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

